"""widen_varchar

Revision ID: 702debef938d
Revises: 0001_initial
Create Date: 2026-02-18 15:01:54.355455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702debef938d'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyst_notes', 'entity_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_contract_parent_id'), 'contract', ['parent_id'], unique=False)
    op.alter_column('lots', 'lot_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('ix_lots_amount', 'lots', ['amount'], unique=False)
    op.alter_column('risk_flags', 'entity_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('risk_flags', 'indicator_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index('ix_risk_flags_indicator', 'risk_flags', ['entity_type', 'entity_id', 'indicator_code'], unique=False)
    op.alter_column('risk_scores', 'entity_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('subject', 'phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('trd_app', 'prot_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_trd_app_lots_lot_id'), 'trd_app_lots', ['lot_id'], unique=False)
    op.create_index(op.f('ix_trd_app_lots_trd_app_id'), 'trd_app_lots', ['trd_app_id'], unique=False)
    op.alter_column('trd_buy', 'number_anno',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_trd_buy_number_anno'), 'trd_buy', ['number_anno'], unique=False)
    op.alter_column('treasury_pay', 'espk',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('treasury_pay', 'gu',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('treasury_pay', 'fin_source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('treasury_pay', 'fin_source',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('treasury_pay', 'gu',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('treasury_pay', 'espk',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_trd_buy_number_anno'), table_name='trd_buy')
    op.alter_column('trd_buy', 'number_anno',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_trd_app_lots_trd_app_id'), table_name='trd_app_lots')
    op.drop_index(op.f('ix_trd_app_lots_lot_id'), table_name='trd_app_lots')
    op.alter_column('trd_app', 'prot_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('subject', 'phone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('risk_scores', 'entity_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('ix_risk_flags_indicator', table_name='risk_flags')
    op.alter_column('risk_flags', 'indicator_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('risk_flags', 'entity_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('ix_lots_amount', table_name='lots')
    op.alter_column('lots', 'lot_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_contract_parent_id'), table_name='contract')
    op.alter_column('analyst_notes', 'entity_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
